import math
import warnings

from itertools import repeat
import collections.abc

import torch
from functools import partial
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.checkpoint as checkpoint
from torch import Tensor

# from timm.models.layers import drop_path, to_2tuple, trunc_normal_

# from .base_backbone import BaseBackbone


def drop_path(x,
              drop_prob: float = 0.,
              training: bool = False,
              scale_by_keep: bool = True):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).

    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.

    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0], ) + (1, ) * (
        x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor


def _ntuple(n):

    def parse(x):
        if isinstance(x, collections.abc.Iterable) and not isinstance(x, str):
            return x
        return tuple(repeat(x, n))

    return parse


to_1tuple = _ntuple(1)
to_2tuple = _ntuple(2)
to_3tuple = _ntuple(3)
to_4tuple = _ntuple(4)
to_ntuple = _ntuple


def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    NOTE: this impl is similar to the PyTorch trunc_normal_, the bounds [a, b] are
    applied while sampling the normal with mean/std applied, therefore a, b args
    should be adjusted to match the range of mean, std args.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    该类实现了 DropPath（随机深度）机制，主要用于残差块的主要路径中。
    """

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob  # 设置丢弃概率

    def forward(self, x):
        # 前向传播，通过 drop_path 函数实现随机丢弃
        return drop_path(x, self.drop_prob, self.training)

    def extra_repr(self):
        # 返回额外信息，包含丢弃概率
        return 'p={}'.format(self.drop_prob)


class Mlp(nn.Module):
    """多层感知器（MLP）模块，包含线性层和激活函数。
    """

    def __init__(self,
                 in_features,
                 hidden_features=None,
                 out_features=None,
                 act_layer=nn.GELU,
                 drop=0.):
        super().__init__()
        out_features = out_features or in_features  # 如果未指定输出特征，则设置为输入特征
        hidden_features = hidden_features or in_features  # 如果未指定隐藏特征，则设置为输入特征
        self.fc1 = nn.Linear(in_features, hidden_features)  # 第一个线性层
        self.act = act_layer()  # 激活函数
        self.fc2 = nn.Linear(hidden_features, out_features)  # 第二个线性层
        self.drop = nn.Dropout(drop)  # dropout 层

    def forward(self, x):
        # 前向传播：线性层 -> 激活函数 -> 线性层 -> dropout
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    """多头自注意力机制。
    """

    def __init__(self,
                 dim,
                 num_heads=8,
                 qkv_bias=False,
                 qk_scale=None,
                 attn_drop=0.,
                 proj_drop=0.,
                 attn_head_dim=None):
        super().__init__()
        self.num_heads = num_heads  # 头的数量
        head_dim = dim // num_heads  # 每个头的维度
        self.dim = dim

        if attn_head_dim is not None:
            head_dim = attn_head_dim  # 如果指定了头的维度，则使用该值
        all_head_dim = head_dim * self.num_heads  # 所有头的维度总和

        self.scale = qk_scale or head_dim**-0.5  # 注意力得分缩放因子

        self.qkv = nn.Linear(dim, all_head_dim * 3,
                             bias=qkv_bias)  # 线性层用于生成 Q, K, V

        self.attn_drop = nn.Dropout(attn_drop)  # 注意力 dropout 层
        self.proj = nn.Linear(all_head_dim, dim)  # 线性层用于投影回原始维度
        self.proj_drop = nn.Dropout(proj_drop)  # 投影后 dropout 层

    def forward(self, x):
        B, N, C = x.shape  # B: 批大小, N: 序列长度, C: 特征维度
        qkv = self.qkv(x)  # 生成 Q, K, V
        qkv = qkv.reshape(B, N, 3, self.num_heads, -1).permute(
            2, 0, 3, 1, 4)  # 重塑并转置为 (3, B, num_heads, N, head_dim)
        q, k, v = qkv[0], qkv[1], qkv[2]  # 分别获取 Q, K, V

        q = q * self.scale  # 应用缩放
        attn = (q @ k.transpose(-2, -1))  # 计算注意力得分

        attn = attn.softmax(dim=-1)  # 计算 softmax 得到注意力权重
        attn = self.attn_drop(attn)  # 应用 dropout

        x = (attn @ v).transpose(1, 2).reshape(B, N, -1)  # 根据注意力权重加权 V，并重塑
        x = self.proj(x)  # 投影回原始维度
        x = self.proj_drop(x)  # 应用投影后 dropout

        return x


class Block(nn.Module):
    """Transformer 的基本构建块，包括自注意力和 MLP。
    """

    def __init__(self,
                 dim,
                 num_heads,
                 mlp_ratio=4.,
                 qkv_bias=False,
                 qk_scale=None,
                 drop=0.,
                 attn_drop=0.,
                 drop_path=0.,
                 act_layer=nn.GELU,
                 norm_layer=nn.LayerNorm,
                 attn_head_dim=None):
        super().__init__()

        self.norm1 = norm_layer(dim)  # 第一个规范化层
        self.attn = Attention(dim,
                              num_heads=num_heads,
                              qkv_bias=qkv_bias,
                              qk_scale=qk_scale,
                              attn_drop=attn_drop,
                              proj_drop=drop,
                              attn_head_dim=attn_head_dim)  # 自注意力层

        # 用于随机深度的 DropPath，如果 drop_path 为 0 则使用 nn.Identity（不做任何操作）
        self.drop_path = DropPath(
            drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)  # 第二个规范化层
        mlp_hidden_dim = int(dim * mlp_ratio)  # MLP 隐藏层维度
        self.mlp = Mlp(in_features=dim,
                       hidden_features=mlp_hidden_dim,
                       act_layer=act_layer,
                       drop=drop)  # MLP 层

    def forward(self, x):
        # 前向传播：规范化 -> 自注意力 -> DropPath -> 残差连接 -> 规范化 -> MLP -> DropPath -> 残差连接
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x


class PatchEmbed(nn.Module):
    """图像到补丁的嵌入层。
    """

    def __init__(self,
                 img_size=224,
                 patch_size=16,
                 in_chans=3,
                 embed_dim=768,
                 ratio=1):
        super().__init__()
        img_size = to_2tuple(img_size)  # 将图像大小转换为元组
        patch_size = to_2tuple(patch_size)  # 将补丁大小转换为元组
        num_patches = (img_size[1] // patch_size[1]) * (
            img_size[0] // patch_size[0]) * (ratio**2)  # 计算补丁数量
        self.patch_shape = (int(img_size[0] // patch_size[0] * ratio),
                            int(img_size[1] // patch_size[1] * ratio))  # 补丁形状
        self.origin_patch_shape = (int(img_size[0] // patch_size[0]),
                                   int(img_size[1] // patch_size[1]))  # 原始补丁形状
        self.img_size = img_size  # 图像大小
        self.patch_size = patch_size  # 补丁大小
        self.num_patches = num_patches  # 补丁数量

        # 使用卷积层将输入通道映射到嵌入维度
        self.proj = nn.Conv2d(in_chans,
                              embed_dim,
                              kernel_size=patch_size,
                              stride=(patch_size[0] // ratio),
                              padding=4 + 2 * (ratio // 2 - 1))

    def forward(self, x, **kwargs):
        B, C, H, W = x.shape  # B: 批大小, C: 通道数, H: 高度, W: 宽度
        x = self.proj(x)  # 通过卷积层进行投影
        Hp, Wp = x.shape[2], x.shape[3]  # 获取投影后的高度和宽度

        x = x.flatten(2).transpose(1, 2)  # 将张量展平并转置
        return x, (Hp, Wp)  # 返回嵌入向量和补丁的高度和宽度


class HybridEmbed(nn.Module):
    """ CNN 特征图嵌入
    从 CNN 中提取特征图，展平并投影到嵌入维度。
    """

    def __init__(self,
                 backbone,
                 img_size=224,
                 feature_size=None,
                 in_chans=3,
                 embed_dim=768):
        super().__init__()
        assert isinstance(backbone, nn.Module)  # 确保 backbone 是 nn.Module 类型
        img_size = to_2tuple(img_size)  # 将 img_size 转换为二元组（height, width）
        self.img_size = img_size  # 保存图像大小
        self.backbone = backbone  # 保存 CNN backbone
        if feature_size is None:
            with torch.no_grad():  # 在不计算梯度的情况下进行推理
                training = backbone.training  # 保存当前训练模式状态
                if training:
                    backbone.eval()  # 将 backbone 设置为评估模式
                # 使用零张量生成特征图
                o = self.backbone(
                    torch.zeros(1, in_chans, img_size[0], img_size[1]))[-1]
                feature_size = o.shape[-2:]  # 获取特征图的空间大小
                feature_dim = o.shape[1]  # 获取特征图的通道数
                backbone.train(training)  # 将 backbone 恢复为原来的训练模式
        else:
            feature_size = to_2tuple(feature_size)  # 将 feature_size 转换为二元组
            feature_dim = self.backbone.feature_info.channels()[
                -1]  # 获取最后一层的通道数
        self.num_patches = feature_size[0] * feature_size[1]  # 计算补丁数量
        self.proj = nn.Linear(feature_dim, embed_dim)  # 创建线性层用于投影到嵌入维度

    def forward(self, x):
        # 前向传播：通过 backbone 提取特征图
        x = self.backbone(x)[-1]  # 获取最后一层的特征图
        x = x.flatten(2).transpose(1, 2)  # 展平特征图并转置
        x = self.proj(x)  # 投影到嵌入维度
        return x  # 返回嵌入特征


class ViT(nn.Module):
    """ Vision Transformer 模型
    """

    def __init__(
        self,
        img_size=224,
        patch_size=16,
        in_chans=3,
        num_classes=80,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4.,
        qkv_bias=False,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.,
        hybrid_backbone=None,
        norm_layer=None,
        use_checkpoint=False,
        frozen_stages=-1,
        ratio=1,
        last_norm=True,
        patch_padding='pad',
        freeze_attn=False,
        freeze_ffn=False,
    ):
        super(ViT, self).__init__()
        # 保护可变默认参数

        norm_layer = norm_layer or partial(nn.LayerNorm, eps=1e-6)  # 规范化层
        self.num_classes = num_classes  # 类别数量
        self.num_features = self.embed_dim = embed_dim  # num_features 与其他模型保持一致
        self.frozen_stages = frozen_stages  # 冻结阶段
        self.use_checkpoint = use_checkpoint  # 使用检查点
        self.patch_padding = patch_padding  # 补丁填充方式
        self.freeze_attn = freeze_attn  # 是否冻结注意力层
        self.freeze_ffn = freeze_ffn  # 是否冻结前馈网络
        self.depth = depth  # Transformer 的层数

        if hybrid_backbone is not None:
            self.patch_embed = HybridEmbed(hybrid_backbone,
                                           img_size=img_size,
                                           in_chans=in_chans,
                                           embed_dim=embed_dim)  # 使用混合骨干网络
        else:
            self.patch_embed = PatchEmbed(img_size=img_size,
                                          patch_size=patch_size,
                                          in_chans=in_chans,
                                          embed_dim=embed_dim,
                                          ratio=ratio)  # 使用标准补丁嵌入
        num_patches = self.patch_embed.num_patches  # 获取补丁数量

        # 因为预训练模型有类别标记，所以需要加一
        self.pos_embed = nn.Parameter(
            torch.zeros(1, num_patches + 1, embed_dim))  # 位置嵌入

        # 随机深度衰减规则
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]

        # 创建多个 Transformer Block
        self.blocks = nn.ModuleList([
            Block(
                dim=embed_dim,
                num_heads=num_heads,
                mlp_ratio=mlp_ratio,
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop=drop_rate,
                attn_drop=attn_drop_rate,
                drop_path=dpr[i],
                norm_layer=norm_layer,
            ) for i in range(depth)
        ])

        self.last_norm = norm_layer(
            embed_dim) if last_norm else nn.Identity()  # 最后的规范化层

        if self.pos_embed is not None:
            trunc_normal_(self.pos_embed, std=.02)  # 初始化位置嵌入

        self._freeze_stages()  # 冻结指定层

    def _freeze_stages(self):
        """冻结参数。"""
        if self.frozen_stages >= 0:
            self.patch_embed.eval()  # 将 patch_embed 设置为评估模式
            for param in self.patch_embed.parameters():
                param.requires_grad = False  # 不更新参数

        # 冻结指定的 block
        for i in range(1, self.frozen_stages + 1):
            m = self.blocks[i]
            m.eval()  # 设为评估模式
            for param in m.parameters():
                param.requires_grad = False  # 不更新参数

        # 冻结注意力层
        if self.freeze_attn:
            for i in range(0, self.depth):
                m = self.blocks[i]
                m.attn.eval()  # 设为评估模式
                m.norm1.eval()  # 设为评估模式
                for param in m.attn.parameters():
                    param.requires_grad = False  # 不更新参数
                for param in m.norm1.parameters():
                    param.requires_grad = False  # 不更新参数

        # 冻结前馈网络
        if self.freeze_ffn:
            self.pos_embed.requires_grad = False  # 不更新位置嵌入
            self.patch_embed.eval()  # 设为评估模式
            for param in self.patch_embed.parameters():
                param.requires_grad = False  # 不更新参数
            for i in range(0, self.depth):
                m = self.blocks[i]
                m.mlp.eval()  # 设为评估模式
                m.norm2.eval()  # 设为评估模式
                for param in m.mlp.parameters():
                    param.requires_grad = False  # 不更新参数
                for param in m.norm2.parameters():
                    param.requires_grad = False  # 不更新参数

    def init_weights(self, pretrained=None):
        """初始化骨干网络中的权重。
        Args:
            pretrained (str, optional): 预训练权重的路径。
                默认值为 None。
        """
        super().init_weights(pretrained, patch_padding=self.patch_padding)

        if pretrained is None:

            def _init_weights(m):
                if isinstance(m, nn.Linear):
                    trunc_normal_(m.weight, std=.02)  # 使用截断正态分布初始化权重
                    if isinstance(m, nn.Linear) and m.bias is not None:
                        nn.init.constant_(m.bias, 0)  # 将偏置初始化为零
                elif isinstance(m, nn.LayerNorm):
                    nn.init.constant_(m.bias, 0)  # 将偏置初始化为零
                    nn.init.constant_(m.weight, 1.0)  # 将权重初始化为1.0

            self.apply(_init_weights)  # 应用初始化函数

    def get_num_layers(self):
        """返回模型中的层数。"""
        return len(self.blocks)

    @torch.jit.ignore
    def no_weight_decay(self):
        """返回不适用权重衰减的参数。"""
        return {'pos_embed', 'cls_token'}

    def forward_features(self, x):
        # 获取输入张量的维度
        B, C, H, W = x.shape  # B: batch size, C: number of channels, H: height, W: width

        # 通过 patch_embed 层对输入进行嵌入，得到嵌入后的特征 x 和特征的高宽 Hp 和 Wp
        x, (Hp, Wp) = self.patch_embed(x)

        # 如果存在位置嵌入
        if self.pos_embed is not None:
            # 适配多 GPU 训练
            # 由于位置嵌入的第一个元素为零（使用正弦-余弦方式），这不会造成任何影响
            x = x + self.pos_embed[:, 1:] + self.pos_embed[:, :1]

        # 遍历所有的块（Transformer Block），对嵌入的特征进行处理
        for blk in self.blocks:
            if self.use_checkpoint:  # 如果启用检查点功能
                x = checkpoint.checkpoint(blk, x)  # 使用检查点来节省内存
            else:
                x = blk(x)  # 直接通过块进行前向传播

        # 对最后的输出进行归一化处理
        x = self.last_norm(x)

        # 重新排列输出张量，准备返回
        xp = x.permute(0, 2, 1).reshape(
            B, -1, Hp, Wp).contiguous()  # 将输出的形状转换为 (B, num_patches, Hp, Wp)

        return xp  # 返回处理后的特征

    def forward(self, x):
        # 调用 forward_features 方法，获取特征
        x = self.forward_features(x)
        return x  # 返回特征

    def train(self, mode=True):
        """Convert the model into training mode."""
        super().train(mode)  # 调用父类的 train 方法
        self._freeze_stages()  # 冻结阶段的参数设置


if __name__ == "__main__":
    input = torch.randn(1,3,256, 196).cuda()
    model = ViT(img_size=(256, 192),
        patch_size=16,
        embed_dim=768,
        depth=12,
        num_heads=12,
        ratio=1,
        use_checkpoint=False,
        mlp_ratio=4,
        qkv_bias=True,
        drop_path_rate=0.3,).cuda()
    
    output = model(input)
    print(output.shape)
